apiVersion: 1

datasources:
  - name: MediaForge Prometheus
    uid: mediaforge-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
