apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaforge-data
  labels:
    app.kubernetes.io/name: mediaforge
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mediaforge-rwx
  resources:
    requests:
      storage: 100Gi
