apiVersion: v1
kind: Service
metadata:
  name: mediaforge-api
  labels:
    app.kubernetes.io/name: mediaforge
spec:
  selector:
    app.kubernetes.io/name: mediaforge
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8020
      targetPort: http
